const translations = {
    pt: {
        nav_about: "Sobre",
        nav_projects: "Projetos",
        nav_links: "Links",
        nav_contact: "Contato",
        nav_contact_desc: "Fale com a RCT",
        hero_text1: 'CRIAMOS IDEIAS<br><span class="white">DO ZERO.</span>',
        hero_text2: "Games, websites e projetos digitais com foco em identidade, \nsimplicidade e experiências marcantes.",
        btn_projects: "Ver projetos",
        btn_about: "Conhecer a RCT",
        reveal1: "SOBRE",
        title_grid: "PEQUENA EQUIPE.<br>GRANDES IDEIAS.",
        about_text1: "A <strong>RCT Roxy Team</strong> é uma equipe independente focada em \ncriar jogos, sites e experiências digitais com personalidade própria.",
        about_text2: "Nosso objetivo é transformar ideias simples em projetos polidos,\nmemoráveis e prontos para chegar ao públic",
        stats1: "Primeiro game em desenvolvimento",
        stats2: "Áreas criativas principais",
        stats3: "Ideias para construir",
        reveal2: "PROJETOS",
        project1_desc: "Empilhe, adapte e quebre as regras em uma experiência de quebra-cabeça roguelike \nconstruído em torno de habilidades poderosas, corridas imprevisíveis e combinações infinitas.",
        project1_text: "EM BREVE",
        project2_desc: "Um protótipo jogável da RCT disponível online. Abra a demo no navegador \ne teste diretamente sem precisar instalar nada.",
        project2_text: "Abrir Inkshot",
        socials_text: "Encontre a RCT",
        socials_desc: "Primeiro, os canais oficiais da RCT. Abaixo, você também encontra os criadores do projeto.",
        links_title1: "Canais oficiais",
        links_title2: "Criadores",
        links_title3: "Comunidade",
        creator_bio1: "Criador da RCT, responsável por direção criativa, projetos digitais,\nconteúdo e desenvolvimento das ideias da equipe.",
        creator_bio2: "Criador da RCT e colaborador dos projetos da equipe.",
        contact_title: "Tem uma ideia?<br>Fale com a RCT.",
        btn_email: "Enviar e-mail",
        contact_social1: "Entre na comunidade oficial da RCT e acompanhe projetos, desenvolvimento e novidades.",
        contact_social2: "Comunidade do Império Astral de Tavix."
    },
    en: {
        nav_about: "About", 
        nav_projects: "Projects", 
        nav_links: "Links", 
        nav_contact: "Contact", 
        nav_contact_desc: "Contact RCT", 
        hero_text1: 'WE CREATE IDEAS<br><span class="white">FROM SCRATCH</span>', 
        hero_text2: "Games, websites and digital projects with a focus on identity, simplicity and remarkable experiences.", 
        btn_projects: "View projects", 
        btn_about: "Get to know RCT", 
        reveal1: "ABOUT",
        title_grid: "SMALL TEAM.<br>BIG IDEAS.", 
        about_text1: "<strong>RCT Roxy Team</strong> is an independent team focused on \ncreating games, websites and digital experiences with their own personality.", 
        about_text2: "Our goal is to transform simple ideas into polished,\nmemorable projects ready to reach the public", 
        stats1: "First game in development", 
        stats2: "Key Creative Areas", 
        stats3: "Ideas to build", 
        reveal2: "PROJECTS", 
        project1_desc: "Stack, adapt, and break the rules in a roguelike puzzle experience \nbuilt around powerful abilities, unpredictable races, and endless combinations.", 
        project1_text: "COMING SOON", 
        project2_desc: "A playable RCT prototype available online. Open the demo in your browser\nand try it directly without having to install anything.", 
        project2_text: "Open Inkshot", 
        socials_text: "Find RCT", 
        socials_desc: "First, the official RCT channels. Below, you can also find the project creators.", 
        links_title1: "Official channels", 
        links_title2: "Creators", 
        links_title3: "Community", 
        creator_bio1: "Creator of RCT, responsible for creative direction, digital projects,\ncontent and development of the team's ideas.", 
        creator_bio2: "Creator of RCT and collaborator on the team's projects.", 
        contact_title: "Do you have an idea?<br>Talk to RCT.", 
        btn_email: "Send email", 
        contact_social1: "Join the official RCT community and follow projects, development and news.", 
        contact_social2: "Tavix Astral Empire Community."
    }
};
export default translations;